server:
  port: 9000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/bf?useUnicode=true&character_set_server=utf8mb4&allowMultiQueries=true
    # TODO The U/P Needs To Be Replaced With Your Own.
    username: root
    password: 1234
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
  redis:
    host: localhost
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  mail:
    username: 2050180797@qq.com
    password: <your-access-password> # TODO The Password Needs To Be Replaced With Your Own.
    host: smtp.qq.com
    default-encoding: UTF-8

